development:
  adapter: postgresql
  encoding: unicode
  database: tbfb_demo_development
  pool: 5
  username: matthew.eagar
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: tbfb_demo_test
  pool: 5
  username: matthew.eagar
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: tbfb_demo_test
  pool: 5
  username: matthew.eagar
  password:
